a, b, c = map(float, input().split())
print("TRIANGULO:",f"{(a*c/2):.3f}")
print("CIRCULO:",f"{c**2*3.14159:.3f}")
print("TRAPEZIO:",f"{(a+b)*c/2:.3f}")
print("QUADRADO:",f"{b*b:.3f}")
print("RETANGULO:",f"{a*b:.3f}")
