var input = require('fs').readFileSync('/dev/stdin', 'utf8');
var lines = input.split('\n');
var prompt = function(texto) { return lines.shift(); };

var valor = Number(prompt());
console.log(valor);
var n100 = parseInt(valor/100);
valor = valor % 100;
var n50 = parseInt(valor/50);
valor = valor % 50;
var n20 = parseInt(valor/20);
valor = valor % 20;
var n10 = parseInt(valor/10);
valor = valor % 10;
var n5 = parseInt(valor/5);
valor = valor % 5;
var n2 = parseInt(valor/2);
valor = valor % 2;
var n1 = parseInt(valor/1);
console.log(`${n100} nota(s) de R$ 100,00`);
console.log(`${n50} nota(s) de R$ 50,00`);
console.log(`${n20} nota(s) de R$ 20,00`);
console.log(`${n10} nota(s) de R$ 10,00`);
console.log(`${n5} nota(s) de R$ 5,00`);
console.log(`${n2} nota(s) de R$ 2,00`);
console.log(`${n1} nota(s) de R$ 1,00`);
